server:
  port: 8082
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migration
  flyway:
    enabled: true
    baseline-version: 1
    locations: classpath:db/migration
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
    sql-migration-prefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}?socketTimeout=3
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver