ALTER TABLE evaluators ADD COLUMN full_name VARCHAR(100) NOT NULL ;
ALTER TABLE evaluators ADD COLUMN nui VARCHAR(20) NOT NULL UNIQUE ;
ALTER TABLE evaluators ADD COLUMN phone VARCHAR(20);
ALTER TABLE evaluators ADD COLUMN birthdate DATE NOT NULL ;
ALTER TABLE evaluators ADD COLUMN gender  VARCHAR(15);